#puerto
server.port=8082


# 1. Configuración de la Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# 2. Configuración de la Conexión
spring.datasource.url=jdbc:h2:mem:ggshop_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Configuración de JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop

# 4. Inicialización de Datos
# Esto asegura que Hibernate cree las tablas antes de que se ejecute el import.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# Swagger UI Config
springdoc.swagger-ui.path=/swagger-ui.html

spring.jpa.open-in-view=true